blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/your-repo/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/your-repo#readme
    about: Read the documentation and guides
